import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        //TODO: write code here
    	Map<String, Integer> map = new LinkedHashMap<String, Integer>();
		for (String item : inputs) {
			String[] str = item.split("x");
			map.put(str[0].trim(), Integer.valueOf(str[1].trim()));
		}
		int sale1 = 0;
		int sale2 = 0;
		int total = 0;
		int saving = 0;
		String str1 = "";
		String str2 = "";
		String str = "============= Order details =============";
		for (Entry<String, Integer> entry : map.entrySet()) {
			if (entry.getKey().equals("ITEM0001")) {
				sale1 += 18 * entry.getValue();
				sale2 += 9 * entry.getValue();
				str1 += "\nBraised chicken x " + entry.getValue() + " = " + 18
						* entry.getValue() + " yuan";
				str2 += "Braised chicken";
				saving += 9 * entry.getValue();
			}
			if (entry.getKey().equals("ITEM0013")) {
				sale1 += 6 * entry.getValue();
				sale2 += 6 * entry.getValue();
				str1 += "\nChinese hamburger x " + entry.getValue() + " = " + 6
						* entry.getValue() + " yuan";
			}
			if (entry.getKey().equals("ITEM0022")) {
				sale1 += 8 * entry.getValue();
				sale2 += 4 * entry.getValue();
				str1 += "\nCold noodles x " + entry.getValue() + " = " + 8
						* entry.getValue() + " yuan";
				if (str2.equals("")) {
					str2 += "Cold noodles";
				} else {
					str2 += "，Cold noodles";
				}
				saving += 4 * entry.getValue();
			}
			if (entry.getKey().equals("ITEM0030")) {
				sale1 += 2 * entry.getValue();
				sale2 += 2 * entry.getValue();
				str1 += "\ncoca-cola x " + entry.getValue() + " = " + 2
						* entry.getValue() + " yuan";
			}
		}

		if (sale1 < 30 && str2.equals("")) {
			total = sale1;
			str = str + str1 + "\n-----------------------------------"
					+ "\nTotal：" + total + " yuan"
					+ "\n===================================";
			return str;
		}

		if (sale1 >= 30) {
			sale1 = sale1 - 6;
		}

		if (sale1 <= sale2) {
			total = sale1;
			str = str
					+ str1
					+ "\n-----------------------------------\nPromotion used:\n满30减6 yuan，saving 6 yuan"
					+ "\n-----------------------------------" + "\nTotal："
					+ total + " yuan" + "\n===================================";
			return str;

		} else {
			total = sale2;
			str = str
					+ str1
					+ "\n-----------------------------------\nPromotion used:\nHalf price for certain dishes ("
					+ str2 + ")，saving " + saving
					+ " yuan\n-----------------------------------\nTotal："
					+ total + " yuan\n===================================";

			return str;
		}
    }
}
